__title__ = "eesampling"
__description__ = "Tools for stratified sampling for comparison groups"
__url__ = "http://github.com/recurve-methods/eesampling"
__version__ = "0.5.5"
__author__ = "Recurve Analytics, Inc"
__author_email__ = "admin@openee.io"
__license__ =  "Apache 2.0" 
__copyright__ = "Copyright 2020 Recurve Analytics, Inc."
